# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build  # Define Build Stage
  displayName: Build the application
  jobs:  # Jobs within Build Stage (can have multiple jobs)
  - job: Build  # Define a job within Build Stage
    displayName: Build .NET Core application
    steps:
      - script: echo Hello, world!
        displayName: 'Run a one-line script'
      - task: UseDotNet@2
        displayName: 'Install .NET Core SDK'
        inputs:
          version: 8.x
          performMultiLevelLookup: true
          includePreviewVersions: true # Required for preview versions
      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          command: build
          projects: '**/*.csproj'
          arguments: '--configuration $(buildConfiguration)' # Update this to match your needs

- stage: Deploy 
  displayName: Publish the application
  jobs:  # Jobs within Build Stage (can have multiple jobs)
    - job: Deploy  # Define a job within Build Stage
      displayName: Deploy .NET Core application
      steps:
        - script: echo Hello, world!
          displayName: 'Run a one-line script'
        - task: DotNetCoreCLI@2
          displayName: Publish
          inputs:
            command: publish
            publishWebProjects: True
            arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
            zipAfterPublish: True



